CREATE TABLE foods(id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30), image BLOB, links VARCHAR(100));
    
CREATE TABLE user(id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(60), password VARCHAR(60), name VARCHAR(50), email VARCHAR(50));